### ISSUE TITLE
Size menu is not sizing correctly? Content is cutoff.

### ISSUE THREAD

**Issue by joshkerr** [Arasthel/Ghostly#1]
My size menu looks different from yours. Its as if the content is cut off. 

Here is a link where you can see it in action: [bum.io](http://bum.io)

![screen shot 2016-10-13 at 11 32 56 pm](https://cloud.githubusercontent.com/assets/17816/19375805/95555dc8-919d-11e6-80f0-d0be7101a3ce.png)

**Comment by jmartinesp** [comment]
It looks fine to me:

![](https://i.imgur.com/oBhL78R.png)

Are you sure you don't have cache issues?
