### ISSUE TITLE
REQ: variable to turn on MathJax support. (Its latex formatting.)

### ISSUE THREAD

**Issue by joshkerr** [Arasthel/Ghostly#2]
You can read more about it [here](https://www.mathjax.org/).

I'd love to see support for Mathjax in this theme. You would simply need to add a line of javascript to the post template. You can see it in action on my [blog](http://www.bum.io/grahams-number-an-enormous-number/).

**Comment by jmartinesp** [comment]
I'm quite sure this can be done using the `Code Injection` section of the Admin page. You could just paste the script tag into the _Blog Header_ textbox and it will be injected to every page.
