### ISSUE TITLE
Unable to load disqus via https

### ISSUE THREAD

**Issue by asle** [Arasthel/Ghostly#3]
I get the error: We were unable to load Disqus and. When I click on "troubleshooting guide" I get an error on loading "https://cloud.typography.com/797702/686420/css/fonts.css" saying it does not exist. 
I also get error loading "count.js" with message ".... net:ERR_INSECURE_RESPONSE". I have not added any other code except i the header:

var disqus_shortname = 'asle-benoni-no.disqus.com';

Any idea where to troubleshoot?

**Comment by dexafree** [comment]
If you can link us to the website where you set the theme, we can try to guess what's happening.
By now, please try removing the `.disqus.com` part.

**Comment by asle** [comment]
https://asle.benoni.no

**Comment by asle** [comment]
Wow! Thanks for the fast reply! Removing the `.disqus.com` fixed it!
