### ISSUE TITLE
Comment count for Disqus?

### ISSUE THREAD

**Issue by frippz** [Arasthel/Ghostly#4]
Got the Disqus comments working swimmingly, but didn't find any comment count in the feed. Is this perhaps something I will have to add myself?

Cheers!

**Comment by jmartinesp** [comment]
Yes, that isn't included on the theme so you'll have to add it manually. Right now I don't have time to look at this, but feel free to PR if you get it working.

**Comment by frippz** [comment]
I chose another theme in the end, but I think I'll have a look at it anyway, just for the fun of it. Thanks!
